services:
        app:
                image: challenge-dockerapp
                build:
                        context: .
                        dockerfile: ./Dockerfile.node
                container_name: challenge-app
                entrypoint: dockerize -wait tcp://db:3306 node index.js
                expose:
                        - "3000"
                networks:
                        - appproxynet
                        - appdbnet
                env_file:
                        - db/db.env
                restart: always
                depends_on:
                        - db
        reverse_proxy:
                image: challenge-dockerproxy
                build: 
                        context: .
                        dockerfile: ./Dockerfile.nginx
                container_name: challenge-reverseproxy
                ports:
                        - "8080:8080"
                networks:
                        - appproxynet
                restart: always
        db:
                image: mysql
                container_name: challenge-db
                expose:
                        - "3306"
                networks:
                        - appdbnet
                env_file:
                        - db/db.env
                restart: always
networks:
        appproxynet:
                driver: bridge
        appdbnet:
                driver: bridge
