FROM node:lts-alpine

ENV PORT=3000

WORKDIR /app

RUN npm init -y && npm i express
RUN echo -e "const express = require('express');\nconst app = express();\nconst port = $PORT;\n\napp.get('/', (req, res) => { res.send('<h1>Full Cycle Rocks!</h1>') });\n\napp.listen(port);" > index.js

EXPOSE $PORT
